### ISSUE TITLE
Unable to install nimbusml

### ISSUE THREAD

**Issue by rkbairi** [microsoft/NimbusML#104]
Trying to install nimbusml:
`pip install nimbusml`

I am running into the following error:

```
 Could not find a version that satisfies the requirement nimbusml (from versions: )
No matching distribution found for nimbusml
```

My Python version:
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

My Windows version:
Windows Server 2016, Version 1607.

Windows Server not supported? Has anyone tried to install it on Windows Server?

Any thoughts?

**Comment by skasturi** [comment]
Thanks for trying. Support for Python 3.7 is still WIP.

Please refer to #103

**Comment by rkbairi** [comment]
Thanks for this info. I was looking into [https://github.com/Microsoft/NimbusML#installation] . This link said  
`nimbusml requires Python 2.7, 3.5, 3.6, or 3.7, 64 bit version only.`

Will create a Python 3.6 environment and try.

Thanks!

**Comment by skasturi** [comment]
@rkbairi Thanks for pointing out. 

@ganik, @justinormont  We might want to fix the installation page that says Python 3.7 is already supported.

**Comment by xadupre** [comment]
The build is working, we should probably update pypi with the Wheel for 3.7.

**Comment by ganik** [comment]
I have removed 3.7 from installation page for now. WIll put it back once 3.7 version is in PyPi

**Comment by shmed** [comment]
Now that 3.7 is supported, is it expected that pip install would work on a python 3.7.X environment? Because as of now, I'm still hitting the same issue as above:
D:\source\ranking\notebooks> pip3 -V
pip 19.3 from c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
D:\source\ranking\notebooks> pip3 install nimbusml
ERROR: Could not find a version that satisfies the requirement nimbusml (from versions: none)
ERROR: No matching distribution found for nimbusml

Using python 3.7.3
Not going to put the full verbose output, but here's the relevant parts:
D:\source\ranking\notebooks> pip3 install nimbusml -v
Created temporary directory: C:\Users\ramero\AppData\Local\Temp\pip-ephem-wheel-cache-wik9slk7
Created temporary directory: C:\Users\ramero\AppData\Local\Temp\pip-req-tracker-6fxs42gp
Created requirements tracker 'C:\\Users\\ramero\\AppData\\Local\\Temp\\pip-req-tracker-6fxs42gp'
Created temporary directory: C:\Users\ramero\AppData\Local\Temp\pip-install-sus60wk6
1 location(s) to search for versions of nimbusml:
* https://pypi.org/simple/nimbusml/
Getting page https://pypi.org/simple/nimbusml/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/nimbusml/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/nimbusml/ HTTP/1.1" 304 0
Analyzing links from page https://pypi.org/simple/nimbusml/
  Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  Skipping link: none of the wheel's tags match: cp27-none-macosx_10_11_x86_64: https://files.pythonhosted.org/packages/8d/19/755694fc7359bd555a99801f3fa5aeeb2a8214bee53588c818fe6d2ad792/nimbusml-1.1.0-cp27-none-macosx_10_11_x86_64.whl#sha256=25337eafa678858fa6482a069f4d94b747d834e06f20e0b724edc870d7822cd1 (from https://pypi.org/simple/nimbusml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.8.*)

...

7f69d8898de55ca55ac09598d147441522d62ab0a (from https://pypi.org/simple/nimbusml/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.8.*)
Given no hashes to check 0 links for project 'nimbusml': discarding no candidates
ERROR: Could not find a version that satisfies the requirement nimbusml (from versions: none)
Cleaning up...
Removed build tracker 'C:\\Users\\ramero\\AppData\\Local\\Temp\\pip-req-tracker-6fxs42gp'
ERROR: No matching distribution found for nimbusml
Exception information:
Traceback (most recent call last):
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\commands\install.py", line 381, in run
    resolver.resolve(requirement_set)
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 311, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\req\req_install.py", line 225, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\ramero\appdata\local\programs\python\python37-32\lib\site-packages\pip\_internal\index.py", line 906, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for nimbusml

**Comment by ganik** [comment]
Make sure to use 64 bit python installation. NimbusML wheels are not available for 32 bits

**Comment by shmed** [comment]
Yes thank you @ganik! I realized it after I submitted my comment.
