### ISSUE TITLE
[Roadmap] Python 3.7 support plans for NimbusML

### ISSUE THREAD

**Issue by stevengum** [Microsoft/NimbusML#37]
> @montebhoover What is in your team's plan around support for 3.7? The BotBuilder SDK team is _considering_ moving to Python 3.7 from 3.6; we'd like to be able to run with NimbusML out of the box, should customers decide to use the two together.
> 
> __DCR: Target Python 3.7 instead of Python 3.6 for BotBuilder-Python__ [Microsoft/BotBuilder#5112]

_Originally posted by @stevengum in https://github.com/Microsoft/NimbusML/pull/28#issuecomment-434017015_

**Comment by xadupre** [comment]
Just copy/pasting the comment I added on #28.

I created a branch where I made the necessary changes to compile nimbusml for python3.7 on windows. linux and mac are easy to add but I could not test them (just need to modify csproj and sln files).

https://github.com/Microsoft/NimbusML/tree/py37_11

But:

* I did not want to build with boostpython as it seemed complex to retrieve the necessary binaries, I replaced it with pybind11.
* I used the python standard distribution instead of anaconda (that should not change anything).
* I did not run the whole test series (but so far no issues for the examples I tried)
* The build is not yet finalized as I had to copy ml.net binaries myself to .internal.libs

Conclusion:

* It is almost done.
* CI and build must be completed.
* I can share the wheel I built on Windows based on the branch mentioned above.

**Comment by stevengum** [comment]
Thank you for the update @xadupre!

**Comment by ganik** [comment]
Thank you Xavier, do you plan to finish your changes? I would love to see the PR with all platforms added pybind11 is ok, as far as we have only it (removing boost_python completely) .
I created the PR out of the branch, but build is failing

**Comment by xadupre** [comment]
Thanks for doing it. No sure I can complete that next week but I should be close :) Glad you're ok to replace boost_python by pybind11. So let's say this will be done before 10 days.

**Comment by narfanar** [comment]
#20 and #28 mentioned issues in Python 3.7 that block upgrading. Is this still on the short-term plan?

**Comment by ganik** [comment]
This is has been done by #101
